### ISSUE TITLE
advice api is not working (maybe)

### ISSUE THREAD

**Issue by pavanmanishd** [c-shubh/advice#1]
when i open Github-pages then its only displaying one advice even if i refresh it doesn't change, I don't seem to find any error in code.
But can you check the code once.

**Comment by c-shubh** [comment]
Fixed in f28417168a5c3e57bcb49f20ff2fba781c13b955
You might have to perform a hard reload using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>
